replication/binlogsyncer.go

I think this is correct, since the docs[1] for enabling semi-sync indicate that not all slaves need to support it, even if the msater does.  This does resolve the problem I sort-of-reported in #13, which appears to be two bytes missing from the beginning of the packet at the time the event is parsed.
[1]: https://dev.mysql.com/doc/refman/5.5/en/replication-semisync-installation.html

Only check for semi-sync ack request if semi-sync is enabled for this connection

---

README.md
replication/binlogstreamer.go

I use replication, when use GetEvent to sync from master, the memory usage grow rapidly. the function 
GetEventTimeout use select to get Events from master and use time.After to set timeout, but the two chennel in different goroutine, when the sync channel return, the time.After channel continue to run, so the memory can't be released.
set timeout to 1s， make sure not used too much memory, after 1s, all used memory by time.After will be
collect by garbage collector

set timeout to 1s to avoid memory leak

---

replication/binlogsyncer.go

try to fix https://github.com/siddontang/go-mysql/issues/19

notify to stop syncing in close

---

mysql/mysql_test.go
mysql/parse_binary.go
mysql/resultset.go
replication/row_event.go

Related to Issue #26 the previously merged PR maintains the same return types always int64 for integral and float64 for floats.
This PR will return variable width and also the unsigned versions of types. This is somewhat of a breaking change, so consider if this seems better to you. It means that users will have to check for float32 as well as int8, uint8, ... int64, uint64 when interface{} is returned. The plus is that there's less chance of getting the wrong value. In particular for replication/row_event.go since there's no 'unsigned' meta info, signed is always returned. So an int32 for a value like 0x80000000 cast to uint32 will mean the right thing. Without this PR an int64 returned for a MYSQL 32-bit LONG with value 0x0000000080000000 will return 0xFFFFFFFF80000000 (with sign …

Return u/int8, u/int16, u/int32 (sign-extend Int24), float32, float64 for interface{} as appropriate

---

replication/binlogsyncer.go

When registering as a slave we are using the wrong hostname. It should
be our hostname, not the hostname name of the server we are connecting
to.
Fixed issue with using the wrong variable.

This fixes issue #34. Using the wrong hostname.

---

.gitignore
server/command.go
server/server_test.go
server/stmt.go

I'm add HandleStmtClose method to Handler interface. This method is useful for better handling prepared statements lifetime, otherwise, is not possible make complete mysql proxy

Add HandleStmtClose Handler interface method

---

replication/row_event.go

This confuses the parser and causes a panic.  
https://github.com/mysql/mysql-server/blob/5.7/sql/log_event.cc#L2242
```
SELECT IF(data_type = 'SET', 'yes', 'no') is_set_column, COUNT(*) FROM information_schema.columns GROUP BY 1;
+---------------+----------+
| is_set_column | COUNT(*) |
+---------------+----------+
| no            |    12785 |
| yes           |        1 |
+---------------+----------+
```

Length for MYSQL_TYPE_SET is in bytes, not bits

---

schema/schema.go

date time fields from mysql are being treated as string rather than date time, addresses https://github.com/siddontang/go-mysql/issues/46

Adding datetime column type

---

replication/parser.go
replication/row_event.go

Because now we support retry, we may retry syncing after getting a TableMapEvent, so the next sync will first get a RotateEvent which clears all table map cache, and then the following RowsEvent parsing will fail. 
@qiuyesuifeng

replication: clear table map when end of the statement.

---

server/command.go

修改EmptyHandler的接口未实现完整的bug

---

README.md

In server example, function 'net.Listen("127.0.0.1:4000")'  lack the first parameter netProto

error in server example

---

server/command.go

Cleaning up `Conn` allows further statements such as `if Conn != nil` to act correctly.

Conn cleanup after closing

---

canal/sync.go

If event is FormatDescriptionEvent, then`ev.Header.LogPos` is always 0. We should not update master in that case.

dont update master if FormatDescriptionEvent

---

replication/binlogsyncer.go

I need  run [go-mysql-elasticsearch](https://github.com/siddontang/go-mysql-elasticsearch) as a daemon service, but I find some time the sync stoped. Below is the log:
`2017/01/17 12:51:08 binlogstreamer.go:47: [error] close sync with err: invalid stream header þ`
`2017/01/17 12:51:08 canal.go:151: [error] canal start sync binlog err: invalid stream header þ`
I can't find out what cause canal stoped, but can we log it instead stop it?

log unkonw stream header instead quit

---

replication/replication_test.go
replication/row_event.go

refer #109 
Hi @eLco @shlomi-noach 
Now I just support decode the geometry type to a bytes, you must decode to the real bytes (Point, LineString, etc...) by yourself.
Seem that the bytes format is SRID(4 tyes) + WKB, E.g, a hex string "000000000101000000000000000000F03F000000000000F03F" is for "POINT(1, 1)", First 4 bytes "00000000" is for SRID and latter is for WKB, you can use some existing go lib to parse it or use the MySQL function like "GeoFromWKB".

replication: support geometry

---

client/auth.go
client/client_test.go
client/conn.go
replication/binlogsyncer.go

This commit updates mysql client authentication to (optionally) support
TLS/SSL connections to the database. To activate, provide tls.Config
when calling client.Connect.
Changes to client/auth.go were copied from the official go-sql-driver.
https://github.com/go-sql-driver/mysql/blob/master/packets.go#L226

support TLS/SSL authentication to the database

---

canal/canal.go
canal/canal_test.go
canal/sync.go

module Canal:
When received a replication.QueryEvent, check if it is ALTER TABLE Query.
If true, clear the table cache
add test into canal_test.go

canal add auto ClearTableCache when table structure changed

---

replication/row_event.go

Hi @shyiko 
I find that you have already used `meta` instead of `4` to calculate the JSON length, so I change it too. But I have no time to port all your tests, maybe later. 
But very interesting that I find the MySQL source code in `log_event_print_value`:
```
case MYSQL_TYPE_JSON:
my_snprintf(typestr, typestr_length, "JSON");
if (!ptr)
return my_b_printf(file, "NULL");
length= uint2korr(ptr);
my_b_write_quoted(file, ptr + meta, length);
return length + meta;
```
Seem that MySQL use 2 bytes to calculate the length, but it can't work in my test if I use 2 too.
/cc @shlomi-noach This may be a risk for JSON type ,although now I for all my test the meta is 4.

repliaction: use meta to calculate length

---

replication/parser.go

Avoid calling *BinlogParser.Reset() in *BinlogParser.ParseReader()
see: https://github.com/siddontang/go-mysql/pull/132 for discussion
This allows streaming data into the parser from files incrementally instead of all at once.

Stop doing a Reset() in ParseReader. It is unnecessary and limiting

---

replication/parser.go
replication/row_event.go

It turns our that when MySQL writes its binary log files that during log file rotation MySQL can and will put the table map event at the end of one file with some or all of the rows events at the beginning of the next file (after the FDE's of course.)  I am not sure if this is possible to encounter when pretending to be a MySQL slave to a MySQL master and streaming the logs that way but it's 100% possible when dealing with the files themselves.
It also turns out that when an event fails parsing that we're returning what looks like a success from ParseData (a nil error because of the break instead of a return.)

Handle when missing table map at log start

---

canal/canal.go
canal/dump.go
canal/handler.go
canal/master.go
canal/sync.go
replication/binlogsyncer.go

https://github.com/siddontang/go-mysql/issues/144
- Add a Canal entry function for GTID
- Provide GTID in `masterInfo`
- Handle GTID events
- Fix typo `writeBinglogDumpCommand` -> `writeBinlogDumpCommand`

Canal starts sync by GTID

---

schema/schema.go
schema/schema_test.go

This will allow people to distinguish an unsigned and signed column without having to examine `RawType` like this:
```
if strings.Contains(column.RawType, "unsigned") {
// uint
} else {
// int
}
```

Added IsUnsigned to TableColumn

---

schema/schema.go
schema/schema_test.go

The current `schema` package should be able to be used independently of the other packages here. However, this is not true in the current implementation as in order to create a new `schema.Table`, it requires something that implements `mysql.Executor` as a connection. As far as I can tell, this requires `mysql.Client`.
Since it is likely that many people will use the default `*sql.DB` as their method of accessing mysql elsewhere in their code base, this means one must open a new connection to the database using `mysql.Client` if they want to use the `schema` package, which is not really ideal.
This PR allows `schema.NewTable` to accept a `*sql.DB` object and use that to fetch the table schema. 
The current draw back is the code is kind of duplicated, although I'm not sure how to make it …

schema.NewTable using regular golang *sql.DB

---

canal/canal.go
canal/canal_test.go
canal/config.go
cmd/go-canal/main.go
mysql/error.go
mysql/mysql_test.go
replication/binlogsyncer.go

When the network jitter or other reasons, the mysql server does not kill invalid canal database connection, which can cause waste of resources, at the same time, with the heartbeat set, canal initiative to kill invalid connection, and to connect to the database

add master slave heartbeat and kill invalid thread id

---

replication/binlogsyncer.go

For my project, it is useful to have a reference to the next position that the syncer will read from :)

Expose public method for syncer's next position

---

canal/canal.go
canal/config.go
dump/dump.go

This is required if needing to increase the default max_packet_size for mysqldump, otherwise I see
```mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table```
Thanks!

Add MaxAllowedPacketMB config to mysqldump args

---

.travis.yml
canal/canal.go
cmd/go-mysqlbinlog/main.go
replication/backup.go
replication/binlogstreamer.go
replication/binlogsyncer.go
replication/replication_test.go

Use package "context" to replace "golang.org/net/x/context".

use context to replace golang.org/net/x/context

---

replication/binlogsyncer.go

This reverts https://github.com/siddontang/go-mysql/commit/0baad4d700af91f9031f5b4e3135f4eb53ed35ce.
Setting a global log level in an initializer causes unwanted side effects in many cases. User who needs this should do `log.SetLevelByString` in main program only.

TWEAK: do not set global log level in NewBinlogSyncer

---

canal/canal.go

```
==================
WARNING: DATA RACE
Write at 0x00c420240558 by goroutine 23:
github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal.(*masterInfo).Update()
/home/ubuntu/go/src/github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal/master.go:22 +0x112
github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal.(*Canal).tryDump()
/home/ubuntu/go/src/github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal/dump.go:130 +0x777
github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal.(*Canal).run()
/home/ubuntu/go/src/github.com/uservoice/indexer/vendor/github.com/siddontang/go-mysql/canal/canal.go:157 +0x7b
Previous read at 0x00c420240558 by goroutine 29: …
```

BUGFIX: data race on master.pos

---

canal/sync.go
failover/mariadb_gtid_handler.go
mysql/mariadb_gtid.go
mysql/mariadb_gtid_test.go
mysql/mysql_gtid.go
mysql/mysql_test.go

Fix a bug ([here](https://github.com/siddontang/go-mysql/blob/c951d16871eb6829d4f53256e05cde906498428e/mysql/mariadb_gtid.go#L82))
use pointer receiver instead of value receiver.

Fix update MariaDB GTID

---

canal/canal.go
canal/canal_test.go
canal/sync.go
cmd/go-canal/main.go

Origin Start will run Canal in another goroutine so we can't know whether it is still running or not, so here we export Run directly. When the Run returns, we can know that Canal meets an error or is closed.
To fix #183

canel: remove Start and use Run

---

replication/parser.go

if function ParseFile called with offset more than 4 then FormatDescriptionEvent would not be read because of the offset. Now FDEvent will be read by default if offset greater than 4

FormatDescriptionEvent should be readed by binlog file always

---

replication/binlogsyncer.go

Currently, when `replication.BinlogSyncer ` closes, it doesn't close the connection showed in `show processlist` which may cause resources waste.  So, I want to expose `LastConnectionID` so the outer caller can kill the connection id when the connection is no longer need. 
According to mysql doc, the creater can kill the connection it created(SUPER privilege is not required).
```
If you have the PROCESS privilege, you can see all threads. If you have the SUPER privilege, you can kill all threads and statements. **Otherwise, you can see and kill only your own threads and statements**.
```

replication: expose last connectionID

---

dump/dump_test.go
dump/parser.go

字段内容中包含 ";"时，会触发解析bug，导致解析的Sql语句不完整。
例如：
INSERT INTO test  (id, title, content, tenum, tset) VALUES (?, ?, ?, ?, ?)", 1, "first", "hello mysql; 2", "e1", "a,b")

fix parse bug

---

server/command.go
server/command_test.go
server/server_test.go

This PR extends `Handler` interface in the `server` package to have a method for handling commands not yet handled by the library.
This allows users of this library to implement extra functionality without extending `server` package. In my case I needed to handle `COM_REGISTER_SLAVE` and `COM_BINLOG_DUMP` commands which can not be easily handled by the `server` package itself.
This is straight forward implementation without caring about package backwards compatibility. If it is merged it will cause breakage for all existing `server` package users until they implement new method.
If breaking old clients is not acceptable we could:
- Create new interface `GenericHandler` with the new method, and try detect if given handler implements additional interface at runtime in `NewConn()`.
- Extend …

Extend Handler interface with generic handler method

---

canal/canal.go
canal/canal_test.go
canal/config.go
dump/dump.go

Sometimes we only want to dump part of data of a single table, and we can use param "--where" to implement it.
```
./mysqldump
-w, --where=name    Dump only selected records. Quotes are mandatory.
```

add mysqldump param --where

---

mysql/gtid.go
mysql/mariadb_gtid.go
mysql/mysql_gtid.go

With the changes introduced in c6f8498, `ParseMariadbGTIDSet` now returns a `*MariadbGTID` (rather than `MariadbGTID`) wrapped in a `GTIDSet` interface. This fixed a bug around never incrementing the GTID; however, broke the way we store the GTID in various parts of our application as we expected the concrete type.
AFAIK Go does not expose an easy way to access the underlying value of an interface without making it less generic (i.e. casting the `GTIDSet` to either `*MysqlGTIDSet` or `*MariadbGTID`), so I propose adding a `Clone()` method to the `GTIDSet` interface to account for this change in behavior.
Currently, the only other option we have is to track the flavor of the GTID we're passing around and calling `ParseGTIDSet` to create a new one which is not ideal:
```go
clone, _ := …
```

Add Clone() method to mysql.GTIDSet

---

replication/parser.go
replication/replication_test.go

1. use interface directly instead of pointer of interface(make it simple)
2. refine test case to make it robust
@siddontang  PTAL

refine replication/parser and test case

---

replication/binlogsyncer.go
replication/event.go
replication/parser.go

Add an option to verify binlog checksum, and disabled by default, so same behaviour as before.
The user can use `BinlogSyncerConfig.VerifyChecksum` to enable verification.
For MySQL, binlog checksum was introduced since 5.6.2, so before 5.6.2, the value of `FormatDescriptionEvent.ChecksumAlgorithm` is `BINLOG_CHECKSUM_ALG_UNDEF`(undefined).
For MariaDB,
>Checksums are enabled with the binlog_checksum option. Until MariaDB 10.2.1, this was disabled by default. From MariaDB 10.2.1, the option is set to CRC32.
So only when `binlog_checksum = CRC32` and `BinlogSyncerConfig.VerifyChecksum = true` will it works.
@siddontang  @GregoryIan   PTAL

add an option to verify binlog checksum

---

replication/binlogsyncer.go
replication/parser.go
replication/row_event.go
replication/time.go
replication/time_test.go

To get the timestamp in any timezone, in the codebase consuming this library, add (and substitute with the timezone of your choice):
```
func init() {
replication.TimeStringLocation = time.UTC
}
```
Fixes: #63 
Also see: github/gh-ost#182 and Shopify/ghostferry#23
review: @siddontang

Fix replication of TIMESTAMP on non-UTC machines

---

canal/canal.go
canal/config.go

Default is to convert timestamps to string. This is a lossy conversion even
if the timezone is known as DTS information gets lost.
By passing ParseTime to go-mysql/replication, the unix timestamp from the DB
is converted to time.Time. From there, the original timestamp can be retrieved.

canal: Add ParseTime config option

---

canal/sync.go

[fix]: ignore TableNotExistErr when handle onTableChanged;

---

client/client_test.go
replication/binlogsyncer.go
replication/row_event.go
replication/row_event_test.go

fix https://github.com/pingcap/tidb-tools/issues/70
according to the binlog, we should handle it in little end 
i have test more when the set num is 18 (need 3 bytes), but i can't find a doc from mysql about this

row_event.go: fix the set bytes value in revert order

---

replication/parser.go

As we know , In MySQL 5.7.x ， it support the table level MTS known as Logical clock . And the parallel information in the GTID_EVENT , if  we use GTID replication. If we set the gtid_mode off , There will have a Anonymous_Gtid Event for the parallel information。 The ANONYMOUS_GTID_EVENT and GTID_EVENT has the same structure.  So I add the parse logic in parser.go for it . 
We can do more thing if we can get the parallel information.

Update parser.go add the parse code  for ANONYMOUS_GTID_EVENT

---

canal/config.go

This line caused a tricky intermittent test failure for us by creating frequent collisions of random numbers. Plus, it is just a good practice in general to avoid seeding the global RNG in a library function.
Example:
```
func TestA(t *testing.T) {
// init canal (seeds rng)
// some test code that doesn't call rand
}
func TestB(t *testing.T) {
id1 := rand.Intn()
// init canal (seeds rng to original seed if <1s has elapsed)
id2 := rand.Intn()
// id1 == id2
// run an update id1 -> id2 in db, canal does not receive an update event, test fails
}
```

Don't seed global RNG

---

replication/row_event.go

The TableMap event contains optional field data, but the doc https://dev.mysql.com/doc/internals/en/table-map-event.html doesn't show it, so I just ignore handing it.

ignore handling optional field meta

---

canal/canal.go
canal/dump.go
canal/master.go
canal/sync.go
dump/dump.go
dump/parser.go
replication/binlogsyncer.go

Hello.
While working on a script that does replication from mysql to cockroachdb I fixed and improved few things. Below is the list:
1. Fixed parsing of empty binary values in mysqldump output. That values look like (_binary '')
2. Errors occurred during the dump parsing were ignored
3. Error returned from OnPosChanged handler was silently ignored. My OnRow handler stores rows in memory. OnPosSynced handler atomically writes stored rows and position to cockroachdb. There was no way to handle error in such scenario
4. Added SyncedTimestamp method to canal. It's very useful for calculating replication delay. Especially in the cases when some tables ignored in the config.
5. Made it possible to connect to mysql over unix socket 
6. TRUNCATE TABLE queries are passed to OnDDL handler

Fixes and improvements for replication

---

dump/dump.go

I need to specify TCP protocol to get dump to work locally.  This patch adds support for the protocol flag.
@siddontang

Add support for different protocols

---

canal/canal.go
canal/config.go

Adds `MaxReconnectAttempts` to canal config.
```
[2019/01/22 10:06:53] [info] binlogsyncer.go:682 receive EOF packet, retry ReadPacket
[2019/01/22 10:06:53] [error] binlogsyncer.go:623 connection was bad
[2019/01/22 10:06:54] [info] binlogsyncer.go:565 begin to re-sync from (mysql-bin.000029, 154)
[2019/01/22 10:06:54] [info] binlogsyncer.go:195 register slave for master server 127.0.0.1:3306
[2019/01/22 10:06:54] [error] binlogsyncer.go:642 retry sync err: connection was bad, exceeded max retries (1)
[2019/01/22 10:06:54] [error] binlogstreamer.go:77 close sync with err: connection was bad
[2019/01/22 10:06:54] [error] canal.go:216 canal start sync binlog err: connection was bad
```

Add MaxReconnectAttempts to canal config

---

dump/dump.go

https://github.com/siddontang/go-mysql/issues/363
when use mysqldump Resulting in 8 hours less time

mysqldump cause timezone problem#issue363

---

replication/event.go
replication/event_test.go

needing to increase `pos` after parsed `SequenceNumber`.

replication: fix MariadbGTIDListEvent Decode with multi GTIDs

---

canal/canal.go
client/conn.go
client/tls.go
driver/driver.go
dump/dump.go
failover/server.go
mysql/error.go
mysql/mysql_gtid.go
mysql/util.go
packet/conn.go
replication/backup.go
replication/binlogstreamer.go
replication/parser.go
schema/schema.go
server/conn.go
server/server_conf.go
server/ssl.go

Fix function comments following [Effective Go Guidelines](https://golang.org/doc/effective_go.html#commentary)

Fix function comments based on best practices from Effective Go

---

Makefile
mysql/resultset.go

Signed-off-by: siddontang <siddontang@gmail.com>
This bug is introduced by https://github.com/siddontang/go-mysql/pull/27, int24 should be parsed as int32 in binary result. 
To fix https://github.com/siddontang/go-mysql/issues/367

fix parsing int24 in binary result

---

replication/json_binary.go
replication/parser.go
replication/row_event.go
replication/row_event_test.go

fix bug found in https://github.com/pingcap/tidb/issues/8761 , which is similar to a MySQL bug: https://bugs.mysql.com/bug.php?id=88791
add a switch to control whether we will ignore this error during jsonBinaryDecoder decode
When we decode a json binary and meet a `isDataShort` error, we don't have enough context to distinguish whether it is caused by this MySQL bug, so we may miss an unexpected error and return an invalid decode result.
However before we decode a json binary, the length of this value is known in advance from code [replication/row_event.go#L517](https://github.com/siddontang/go-mysql/blob/master/replication/row_event.go#L517) and we can believe the `isDataShort` error is definitely a MySQL bug or binlog data inconsistent.
- Unit test

add compatibility to json decode for generated column

---

canal/canal.go
canal/config.go

I need to fix a specific timezone in the parsed timestamp/datetimes from the canal

Allow canal to set timezone in syncer

---

canal/sync.go

It is a common use case that we have a separate goroutine to update
gtid set. We have to ensure that gtid saver sees updated gtid only
after all the tasks are done in event handlers.

move gtid update after all event handlers are executed

---

canal/canal.go
canal/sync.go

Need a way to track replication delay without duplicating code over each hook

Track canal replication delay with a gauge metric

---

.travis.yml
canal/canal.go
canal/canal_test.go
canal/dump.go
canal/handler.go
canal/sync.go

We want to keep track of the GTID when a transaction has ended or a table has been updated

Allow to synchronise GTIDs 'OnPosSynced'

---

canal/sync.go

For some reason `delay` field introduced in #380 was being updated with `atomic.AddUint32`, although it's a gauge metric.

Replication delay should be updated with atomic.StoreUint32

---

canal/sync.go

fix issue #393 
will skip event if parse failed

canal: skip query  event if parse failed

---

canal/canal_test.go
canal/dump.go
canal/rows.go
go.sum
schema/schema.go

this is port from https://github.com/moiot/gravity/issues/182.
the problem is we use int32 to receive mysql medium int value, which is 3 bytes. When it's unsigned, simply do a type cast is not sufficient.

fix(canal): fix mysql unsigned medium int

---

canal/sync.go

do not sync persistent store when get a fake position

---

.travis.yml
canal/sync.go

CI on travis always meets the following error recently:
```
$ sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
The command "sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"" failed and exited with 1 during .
```
ref: https://travis-ci.community/t/cant-connect-to-local-mysql-server-through-socket-var-run-mysqld-mysqld-sock/3414/2
- add service `mysql` to fix this error
- as `SSL/TLS` is not enabled by default, we run `sudo mysql_ssl_rsa_setup --uid=mysql` to enable …

fix mysql connect error in travis ci

---

replication/row_event.go
replication/row_event_test.go
replication/time.go

Golang standard library doesn't support datetime before `1970-01-01 00:00:00` very well, for example the following code snippet will get result
```
package main
import (
"fmt"
"time"
)
func main() {
var (
year   = 0
month  = 0
day    = 1
hour   = 21
minute = 30
second = 42
)
t := time.Date(year, time.Month(month), day, hour, minute, second, 0, time.UTC)
fmt.Printf("%s\n%d\n", t, t.Unix())
}
```
```
-0001-12-01 21:30:42 +0000 UTC
-62169820158
```
This will affect datetime type replication.
Return the string format of a datetime directly if it is before `1970-01-01 00:00:00`
We may lose time zone conversion for datetime before `1970-01-01 00:00:00`. But the zero datetime (`0000-00-00 00:00:00`) still has this issue before this pr. Users should take their own risks to use these datetime …

replication: support datetime less than unix timestamp zero

---

canal/rows.go
canal/sync.go

It seems that several errors were introduced in the #399 
https://github.com/siddontang/go-mysql/blob/046188b858f9a4b47cdedb11068eb868463fcb75/canal/rows.go#L53-L72
- `i` in L61 is an index of the row, not an index of the column. I guess `index` should be used.
- `i` in L64 is always >= 0 since it's an index of the row. Probably it should be `t` here.
- Weird `return` in L69. I don't know why we must stop processing other rows after we've found a first mediumint column.
- Duplicated code in L65 and L71 could be avoided by combining conditions in L61 and L64.
Also I suggest to rename `index` to `columnIdx`, `t` to `value`.
Fixes #404

fix(canal): fix "Index of range error" for unsigned columns

---

canal/canal.go
replication/binlogstreamer.go
replication/binlogsyncer.go

Closing a canal by calling Close() results in errors as described in #273.
Fix that by explicitly ignoring context cancellation as it's not really
an error, but an expected part of Close().
Also fix the unclosed connection described in #361 by using a
separate connection to kill the binlog streamer.

Fix unclosed conn, shutdown errors

---

replication/binlogsyncer.go
replication/replication_test.go

Refine binlog synchronization retry strategy, make it possible for user to disable retry sync or retry forever.
~After this pr the default retry strategy for BinlogSyncer is no retry (if `MaxReconnectAttempts` is not configurated and use default value zero)~
- add `DisableRetrySync` option, the default behavior for retry strategy is not changed, and user also can disable retry by setting `DisableRetrySync` to true

refine usage of MaxReconnectAttempts in BinlogSyncer

---

packet/conn.go

In terms of priorities  this is a very minor change.
in some cases, like packet/conn.go:83, root cause error is being lost
surfacing original errors is useful for troubleshoot production issues

surface original network errors and create error stacks

---

canal/sync.go

The name of a binlog file received in the fake rotate event must be preserved as it was discussed in #406. 
The decision is based on comments in 
https://github.com/mysql/mysql-server/blob/8e797a5d6eb3a87f16498edcb7261a75897babae/sql/rpl_binlog_sender.h#L235
```
... It contains the name of the binlog we are going to
send to the slave.
Faked rotate event is required in a few cases, so slave can know which
binlog the following events are from.
- The binlog file slave requested is Empty. E.g.
"CHANGE MASTER TO MASTER_LOG_FILE='', MASTER_LOG_POS=4", etc.
- The position slave requested is exactly the end of a binlog file.
- Previous binlog file does not include a rotate event.
It happens when server is shutdown and restarted.
- The previous binary log was GTID-free (does not contain a …
```

fix(canal): Preserve binlog filename received in the fake rotate event

---

client/resp.go

When issuing a long running request with the client,  if the query get killed, `conn.Execute` will be hanging.
How to reproduce:
1. issue such request below
```
conn, _ := client.Connect("127.0.0.1:3306", "root", "", "db")
conn.Ping()
r, err := conn.Execute(`select sleep(1000), id from table`)
if err != nil {
fmt.Println(err)
return
}
```
2. use mysql cli to find the query id with `show processlist;` and kill the query with `kill query id;` 
the program will hang on `conn.Execute` and never return.

fix error handling during querying result rows

---

canal/dump.go

There is enough information during dump to recognize that column is unsigned.
Otherwise there's an error if the number is too big to fit into int64. We should use uint64 and ParseUint.

Fix dump parser to recognize unsigned values, fixes #389

---

canal/canal.go
canal/config.go
dump/dump.go

mysqldump client version 8.0 / MacOS
mysql server version 5.7
```
mysqldump --host=10.100.130.8 --port=3306 --user=liujilei --password=liujilei --master-data --single-transaction --skip-lock-tables --compact --skip-opt --quick --no-create-info --skip-extended-insert --skip-tz-utc --hex-blob --default-character-set=utf8  lingxi_user_account_rds profile_0 profile_1
```
error: 
```
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'lingxi_user_account_rds' AND TABLE_NAME = 'profile_0';': Unknown table 'column_statistics' in information_schema (1109)
```
Becuase column-statistics default value is TRUE, I add a extra option …

fix mysqldump option

---

replication/const.go

Please add some extended events:
**TRANSACTION_CONTEXT_EVENT**
https://dev.mysql.com/doc/dev/mysql-server/latest/classbinary__log_1_1Transaction__context__event.html
**VIEW_CHANGE_EVENT**
https://dev.mysql.com/doc/dev/mysql-server/latest/classbinary__log_1_1View__change__event.html
**XA_PREPARE_LOG_EVENT**
https://dev.mysql.com/doc/dev/mysql-server/latest/classbinary__log_1_1XA__prepare__event.html

Extending binlog events list

---

replication/event.go
replication/parser.go

add previousgtidsevent

---

mysql/resultset.go

ParseText  f[i].Type case statment miss MYSQL_TYPE_LONG type

fix ParseText f[i].Type has no MYSQL_TYPE_LONG

---

cmd/go-canal/main.go

这里是不是应该用大于号，如果是等于0，传入的ignoreTables不就无效了

go-canal: fix len(*ignoreTables) > 0

---

replication/row_event.go

when column type is year with value 0，will be resolved to the wrong value：1900，which is illegal in MySQL, It should be 0 instead.

fix bug: year==0 will be resolved to the wrong value: 1900

---

replication/binlogsyncer.go
replication/parser.go
replication/row_event.go
replication/row_event_test.go

This pr adds some type-related helper methods for `TableMapEvent`. https://github.com/siddontang/go-mysql/issues/479
They should behave the same as `Table_map_log_event::print_columns` (`mysqlbinlog --print-table-metadata`).
And a `flavor` field is added to `BinlogParser` and passed to `TableMapEvent` to distinguish mysql/mariadb, since there are some differences slightly in checking types.

Add some TableMapEvent helper methods

---

mysql/mariadb_gtid.go
mysql/mariadb_gtid_test.go

当 mariadb gtid中包含多个 server id时，由于 Sets是一个map结构，输出 set的顺序随机，导致最终输出的 gtid字符串内容不同。本 PR，在输出前对内容进行排序后输出，保证输出结果的一致。

sort mariadb gtid set

---

client/resp.go

fix a rare bug in Conn.readResultStreaming (when MySQL returns OK_packet after SELECT query)

fix a rare bug in Conn.readResultStreaming

---

client/resp.go

this PR is to fix issue #577 
as I only use client module of this repository and didn't use other modules like replication, server...etc, I'm not sure if this fix may impact the behavior of those modules, need some to review this.

fix: init Resultset in Result when handling ddl statement

---

server/conn.go
server/handshake_resp.go
server/handshake_resp_test.go

For a project of mine I need to be able to read the capabilities and default charset of a client connecting to my server. This PR exposes those 2 properties. Charset perhaps used to be decoded before into a type called `CollationId` but this doesn't exist (anymore) and I'm perfectly fine with the collation ID as an uint8.
I also took the liberty to refactor `readFirstPacket` a bit so it is easier to test its behaviour

expose capability and charset of connections to server

---

server/auth.go
server/auth_switch_response.go
server/conn.go
server/handshake_resp.go

- show client's address rather than server's address
- show `using password: NO` when client does not authenticate

Improved access denied error messages

---

server/command.go
server/resp.go

I'm implementing a server that needs to respect the `CLIENT_MULTI_STATEMENTS` capability and the `MYSQL_OPTION_MULTI_STATEMENTS_ON` and `_OFF` options that can be set through `COM_SET_OPTION`. According to the [docs](https://dev.mysql.com/doc/internals/en/com-set-option.html) it is supposed to return EOF on success so I added a backwards compatible way of handling these commands properly.

return EOF response on COM_SET_OPTION commands

---

server/conn.go
server/handshake_resp.go

Not sure what went wrong trying to rebase #592 so here is a new attempt:
---
When trying to reproduce my issue as I describe in #578 I came across an omission I made in #589: I directly pass the error code to `NewDefaultError` instead of the error message corresponding to that code. My apologies for the poor testing.
Also, I noticed that in a different case, the formatting of the user/address was the wrong way around in the access denied error. This gave 
```
ERROR 1045 (28000): Access denied for user '127.0.0.1:51221'@'root' (using password: NO)
```
and now it correctly gives:
```
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:51259' (using password: NO)
```

fixed access denied error messages

---

replication/row_event.go

fix magic number in https://github.com/go-mysql-org/go-mysql/pull/598 😛

use constant and add comment for magic number 9

---

canal/canal.go

When sql_mode contains ANSI_QUOTES mode the " character can be used to enclose identifiers just like `, causing the error below when queries in lines 389 and 404 run.
```
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"binlog_format"' at line 1
```

Fix error when trying to check binlog settings

---

mysql/mysql_test.go
mysql/util.go

Fix LengthEncodedInt returning the length of 1 for an empty slice

---

schema/schema.go

replication/canal   删除数据时有时候会用到
--
replication/canal sometimes needs this flag when deleting rows

add scheme/Index NoneUnique

---

canal/sync.go

Fix case for ast.TruncateTableStmt to assign Name instead of Schema to node.table otherwise OnTableChanged will be passed empty table value.

Fix ast.TruncateTableStmt node name assignment

---

client/client_test.go
client/stmt.go

if use type json.RawMessage for the args, return fmt.Errorf("invalid argument type %T", args[i]) .
i have write some test .
go-sql-driver/mysql@1.6.0 handle json.RawMessage inside :
```
for i, arg := range args {
// build NULL-bitmap
if arg == nil {
nullMask[i/8] |= 1 << (uint(i) & 7)
paramTypes[i+i] = byte(fieldTypeNULL)
paramTypes[i+i+1] = 0x00
continue
}
if v, ok := arg.(json.RawMessage); ok {
arg = []byte(v)
}
// cache types and values
switch v := arg.(type) {
case int64:
blablablabla.....
```

support insert argument type json.RawMessage

---

client/conn.go

We need more control over how dialing is done - in particular, integrating directly with https://pkg.go.dev/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy

Add ConnectWithDialer

---

client/resp.go

close #535
trigger condition: https://github.com/pingcap/ticdc/issues/3847#issuecomment-992225272
tested on my local MySQL 8.0.17

fix that forget to readOK after writing

---

packet/conn.go
utils/bytes_buffer_pool.go

读取网络包遇到大的 event之后，会导致 buffer冲的很大，之后一直没法释放。从而导致整个程序的内存占用居高不下。
这个PR对这块逻辑做了优化，只缓存比较小的缓存块，避免了这种情况。
--
The buffer will be increased and can't be released when the packet is very big, thus the memory consumption keeps high. 
This PR tries to avoid it.

packet: memory optimization for reading network packet

---

client/client_test.go
client/resp.go
mysql/resultset.go

close #639 (replace) 
close #638 
close #618 
and another fix for #577 with unit test

Fix malformed packet and a panic

---

replication/binlogsyncer.go
replication/replication_test.go

close https://github.com/go-mysql-org/go-mysql/issues/618
~I'll see how to add a test in this repo soon.~ For now the manually test result is 
with this PR
```
MySQL [(none)]> show slave hosts;
+-----------+----------------------+------+-----------+--------------------------------------+
| Server_id | Host                 | Port | Master_id | Slave_UUID                           |
+-----------+----------------------+------+-----------+--------------------------------------+
|       101 | lance6716-nuc10i7fnh | 3306 |         1 | 53cd72fc-5efc-11ec-b783-1c697a65dfdc |
+-----------+----------------------+------+-----------+--------------------------------------+
```
without this PR
```
MySQL [(none)]> show slave hosts;
ERROR 2027 (HY000): Malformed packet
```

Set slave_uuid and replica_uuid

---

mysql/mysql_gtid.go
mysql/mysql_test.go

Add MysqlGTIDSet.Add() and Minus() methods, so it will help users to estimate GTID sets that are stored in binlog file.

Add MysqlGTIDSet.Add() and Minus() methods

---

.golangci.yml
canal/sync.go
client/conn.go
client/resp.go
replication/backup.go
replication/json_binary.go
server/caching_sha2_cache_test.go
server/command.go
server/server_test.go

Enabled govet in golangci config and fixed some low-hanging fruit code issues.
The reason I ended up enabling govet is that I eventually want to enable govet's `fieldalignment` linter to lower the memory footprint of this library. To make the changes more readable, I will do that in a follow up PR later.

enabled govet

---

.golangci.yml
client/resp.go
client/stmt.go
mysql/mysql_test.go
mysql/rowdata.go
replication/event.go
replication/replication_test.go
server/stmt.go

In line with #663, #664 and #665, I enabled the ineffassign linter and fixed some small issues that came from it.

enabled ineffassign in golangci

---

.golangci.yml
canal/canal.go
canal/dump.go
dump/dumper.go
dump/parser.go
replication/event.go

In line with #663 and #664, I enabled the `gosimple` linter and fixed some small issues that came from it.

enabled gosimple in golangci

---

mysql/const.go

In my server implementation, I'm using these constants and felt like they belonged in the library. They're described at:
https://dev.mysql.com/doc/internals/en/com-set-option.html#packet-COM_SET_OPTION

added constants for COM_SET_OPTION

---

client/auth.go
client/auth_test.go
client/conn.go

As promised after #672 this PR brings support for client side connection attributes

support client connection attributes on the client side

---

replication/row_event.go
replication/row_event_test.go

close https://github.com/go-mysql-org/go-mysql/issues/677
Thanks @rudy-gao for finishing all the code work, I just help him file a PR

fix TIME value near zero will become zero

---

utils/bytes_buffer_pool.go

Since sync.Pool already handling data across GC and also in highly concurrent environments the calls to channel may impact performance.

Stop using channel for memory pooling

---

.github/workflows/ci.yml

Github actions support go1.18 as well

Add go1.18 to the test matrix

---

canal/sync.go
go.mod
go.sum
mysql/mysql_gtid.go
replication/binlogsyncer.go
replication/event.go
replication/replication_test.go

Library github.com/satori/go.uuid didn't release new version in 4 years and there is CVE-2021-3538 vulnerability.
This PR replaces github.com/satori/go.uuid dependency with github.com/google/uuid

Replacing github.com/satori/go.uuid with github.com/google/uuid

---

canal/canal.go
canal/config.go
canal/dump.go
canal/master.go
canal/sync.go
replication/binlogsyncer.go

Ideally libraries don't have a logger at all. But this is a smaller change by allowing a user to set the Logger. This will allow the previous behaviour if needed.
Closes: https://github.com/go-mysql-org/go-mysql/issues/698 and maybe others
Should errors ever log or just return?

Allow logger override

---

client/conn.go

The check for tlsConfig being non-nil was in the wrong place. Fixes #705

Fix initialization of TLS connections

---

server/auth_switch_response.go

Through time, I made a couple of changes to a local branch of go-mysql I'm using. While I was casually going over the diffs between my branch and the upstream master, I noticed that I could optimise something: comparing the client's authentication data during the handshake is abstracted to `compareNativePasswordAuthData` for `mysql_native_password` while this is not the case during auth switching. So I think this is duplicate code and can be simplified like this!

use existing function for comparing auth data

---

canal/canal.go
canal/config.go
client/conn.go
replication/binlogsyncer.go

Allow custom dialers in canal in binlog syncer. This change introduces some minor copy&paste code mainly in order to set the timeout context at 10 seconds to mimic the behavior of client.Connect

Add support for custom dialer in canal and binlog syncer

---

cmd/go-canal/main.go
replication/binlogsyncer.go

as title, so we can use ipv6 address more naturally(not workaround with explicit square brackets)

use net.JoinHostPort to join host and port

---

replication/binlogsyncer.go

to make #411 work, we need to use background context since `b.ctx` is already cancelled when we create another connection to kill last conn in `b.close`

use background as base ctx in context.WithTimeout 

---

.github/workflows/ci.yml
canal/canal.go
canal/config.go
client/auth.go
client/client_test.go
client/conn.go
client/pool.go
driver/driver.go
dump/schema_test.go
failover/failover.go
packet/conn.go
server/caching_sha2_cache_test.go
server/conn.go

The package `io/ioutil` has been deprecated since Go 1.16

removed use of deprecated ioutil

---

client/conn.go
client/conn_test.go

Client FieldList is missing the first field because check ERR Packet.
Check ERR Packet in loop, in this way we can parse the first packet into FieldData

fix: fix client field list

---

packet/conn.go

defer capture arguments at once, so modify arguments after defer line not works
Closes #728

packet: fix misusing of defer

---

canal/config.go
canal/master.go
replication/binlogsyncer.go

It is much easier to integrate 3rd-party log implementations by requiring an interface instead of requiring a Logger struct (which implements this interface).

Make logger require an interface instead of a concrete implementation

---

README.md
canal/canal_test.go
client/client_test.go
client/resp.go
client/stmt.go
driver/driver_test.go
failover/mariadb_gtid_handler.go
failover/mysql_gtid_handler.go
mysql/field.go
mysql/resultset_helper.go
replication/binlogsyncer.go
replication/const.go
replication/event.go
replication/json_binary.go
replication/row_event.go
replication/row_event_test.go
server/conn_test.go
server/resp_test.go

Hi there, 
I added some tweaks before using the library in the code. Please Addin changes.
These are primarily refractory changes.

Code refractoring

---

mysql/gtid.go
mysql/mariadb_gtid.go
mysql/mysql_gtid.go
mysql/mysql_test.go
replication/binlogsyncer.go

- add InsertInterval for mysql gtidset

speed up gtid process for mysql

---

canal/canal.go

If we do not use `canal.NewDefaultConfig()`, then the client will crash:
**When Logger is nil**
```text
[2022/11/26 19:48:41] [info] binlogsyncer.go:156 create BinlogSyncer with config {999 mysql 10.43.173.151 3306 root    false false <nil> false UTC false 0 0s 0s 0 false false 0 <nil> 0xc00011b320}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5d1a45]
goroutine 1 [running]:
github.com/siddontang/go-log/log.(*Logger).Output(0x6bc30e?, 0xd?, 0x0?, {0xc00011ca40?, 0x0?})
/home/fang/go/pkg/mod/github.com/siddontang/go-log@v0.0.0-20180807004314-8d05993dda07/log/logger.go:137 +0x45
github.com/siddontang/go-log/log.(*Logger).Infof(0x0?, {0x6bc30e?, 0x0?}, {0x0?, 0xc000147f50?, 0x645db8?}) …
```

fix panic when logger or dialer is not set in canal config

---

canal/canal.go
canal/canal_test.go
canal/dump.go
canal/handler.go
canal/sync.go

add EventHandlerV2 to get timestamp from event, so that canal can show the how much time delay when process like
```go
func (s *handler) OnXID(header *replication.EventHeader, nextPos mysql.Position) error {
s.queue <- model.Position{
Name:      nextPos.Name,
Pos:       nextPos.Pos,
Timestamp: header.Timestamp,
Force:     false,
}
return nil
}
```
it can show on UI like
binlog file: mysql-bin.000102
binlog position: 1142900
**binlog timestamp: 2022-11-25 15:54:07 (1669362847)**
**tiem delay:  2 sec**

EventHandlerV2 support handle event with replication.EventHeader

---

replication/binlogsyncer.go

- add DiscardGTIDSet to allow user not to maintain Gset for QueryEvent/XIDEvent
- add prevMySQLGTIDEvent to calculate prevGSet instead of clone currGSet

binlog_syncer: reduce the times of Clone of MySQLGTIDSet to speed up

---

canal/sync.go

Fix https://github.com/go-mysql-org/go-mysql/issues/752

handle fake rotate event as real if binlog filename changed

---

client/auth.go
mysql/const.go

This is required to connect with Amazon RDS MySQL databases that only supports clear password over TLS.

Support "mysql_clear_password" auth plugin

---

Makefile
canal/canal_test.go
client/client_test.go
client/common_test.go
client/conn_test.go
docker/resources/replication.cnf
docker/resources/waitfor.sh
driver/driver_test.go
dump/schema_test.go
dump/setup_test.go
failover/failover_test.go
mysql/mysql_test.go
replication/backup_test.go
replication/replication_test.go
schema/schema_test.go
server/caching_sha2_cache_test.go
server/server_test.go
test_util/flags.go
utils/utils_test.go

We can run our tests on CI stage (github actions). But it's difficult for local usage 😅
Now I'm working on [#650](https://github.com/go-mysql-org/go-mysql/issues/650) and I really need tests locally.
I'm trying to use [act](https://github.com/nektos/act), but it's not working for me.
So I wrote a docker env for it. Also, I did tiny refactoring and fixes in tests for it.
All we need to run tests is simple `$ make test-local`.

Allow to run tests in local environment + fix tests for it

---

replication/binlogsyncer.go

Example code:
```go
package main
import "github.com/go-mysql-org/go-mysql/replication"
func main() {
cfg := replication.BinlogSyncerConfig{
ServerID: 100,
Flavor:   "mysql",
Host:     "127.0.0.1",
Port:     3306,
User:     "root",
Password: "secret",
}
replication.NewBinlogSyncer(cfg)
}
```
Without this PR:
```
[2023/01/27 11:58:30] [info] binlogsyncer.go:173 create BinlogSyncer with config {100 mysql 127.0.0.1 3306 root    false false <nil> false UTC false 0 0s 0s 0 false false 0 <nil> 0xc0000ac180 0x52a420 <nil> false}
```
With this PR:
```
[2023/01/27 11:56:31] [info] binlogsyncer.go:170 create BinlogSyncer with config {"ServerID":100,"Flavor":"mysql","Host":"127.0.0.1","Port":3306,"User":"root","Password":"\u003chidden\u003e","Localhost":"","Charset":"","SemiSyncEnabled":false,"RawMode …
```

binlogsyncer: Format config in logs

---

canal/sync.go
mysql/util.go
replication/const.go
replication/event.go
replication/parser.go
replication/row_event.go

This would fix https://github.com/go-mysql-org/go-mysql/issues/204
Events doc: https://mariadb.com/kb/en/rows_event_v1v2-rows_compressed_event_v1/
Based on [this](https://github.com/mariadb-corporation/mariadb-connector-c/blob/c2b322d2ca27ef66385d9938b98541c7cf14ac74/libmariadb/mariadb_rpl.c#L861) and [this](https://github.com/mariadb-corporation/mariadb-connector-c/blob/c2b322d2ca27ef66385d9938b98541c7cf14ac74/libmariadb/mariadb_rpl.c#L1771-L1789)

Add support for MariaDB compressed binlog events

---

client/conn.go
replication/binlogsyncer.go

Set connection attributes like `_platform`, `_os`, `_client_name`, etc. by default. 
Have `SetAttributes()` update the map instead of overwriting it.
This makes it behave similar to other MySQL clients.
See also: https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html
Wireshark:
Example:
```go
package main
import "github.com/go-mysql-org/go-mysql/client"
func main() {
conn, _ := client.Connect("127.0.0.1:4000", "root", "", "test", func(c *client.Conn) {
c.SetAttributes(map[string]string{"app": "myapp"})
})
conn.Ping()
conn.Close()
}
```

Set library specific connection attributes

---

client/auth.go
client/resp.go
mysql/field.go

Make `LOAD DATA LOCAL INFILE` available.

Support LOCAL INFILE request

---

.github/workflows/ci.yml
go.mod
go.sum
packet/conn.go
replication/transaction_payload_event.go

Closes #799 
- Allow build on ARM64
- Switch from `github.com/DataDog/zstd` to `github.com/klauspost/compress`
- Change go version from 1.16 to 1.18 in `go.mod`
- Add basic CI tests for building for various OS and Arch combinations
Note that this basically removes support for older versions of Go (1.17 and 1.16)

Switch zstd library to allow build on arm64 and amd64

---

server/handshake_resp.go
server/handshake_resp_test.go

This PR resolves a panic in decodeFirstPart when the functions receives malformed data.
```
panic: runtime error: slice bounds out of range [:2] with capacity 0
```

fix: prevent panic on malformed handshake

---

cmd/go-binlogparser/main.go
cmd/go-canal/main.go
cmd/go-mysqlbinlog/main.go
cmd/go-mysqldump/main.go

I've changed the form of variable declarations which make the code look better (maybe...) 
the comparison is following :
before:
```go
var host = flag.String("host", "127.0.0.1", "MySQL host")
var port = flag.Int("port", 3306, "MySQL port")
var user = flag.String("user", "root", "MySQL user, must have replication privilege")
var password = flag.String("password", "", "MySQL password")
```
after:
```go
var (
host     = flag.String("host", "127.0.0.1", "MySQL host")
port     = flag.Int("port", 3306, "MySQL port")
user     = flag.String("user", "root", "MySQL user, must have replication privilege")
password = flag.String("password", "", "MySQL password")
)
```
I am not sure if this change is necessary, but if not, please ignore. :)
thank u for reviewing. 🫡

refactor: modify the form of variable declarations

---

client/client_test.go
mysql/field.go

close https://github.com/go-mysql-org/go-mysql/issues/821

add String() for FieldValue

---

canal/config.go
mysql/const.go
mysql/position.go

I found the code comments of this program are not enough which make the program hardly to understand...
so I add some code comments through my understanding of the program.
I just remove the mysql default constant to the same file.

feat:add code comments & refactor mysql config constant

---

canal/sync.go

When using canal to handle MySQL 8.0 Compressed binlog, I find that it could not get any row.
Hope that we can support handle TransactionPayloadEvent in canal, not just in replication package

feat: handle subevents in transaction payload event

---

replication/binlogstreamer.go
replication/binlogsyncer.go

#829 
I have tested on my own MySQL instance with an 8GB size Binlog, when the channel size is the default 10240, during the Binlog transmission, occasional nearly 2GB memory usage will be seen. 
Additionally, I have written a test program to calculate the theoretical maximum memory usage size under different channel size situations.  The theoretical result match the test. 
This is the theoretical usage calc function: 
`
func (c *MySQLClient) GetMaxWindowSize(ctx context.Context, streamerLength uint16) (es *EventStatistic, err error) {
es = new(EventStatistic)
es.StreamerChannelLength = streamerLength
startTime := time.Now()
// get streamer
_, streamer, err := c.GetBinlogStreamer(true, streamerLength)
if err != nil {
return nil, err
}
// defer syncer.Close()
defer func() {
es.Duration = …

Add EventCacheCount as member of BinlogSyncerConfig to limit streamer's event channel size

---

canal/canal.go
replication/row_event.go

NOTE: this PR is untested atm, hence why it is a draft
This PR changes `canal` to skip decoding `RowsEvent` events for tables that it is not interested in (cfr `IncludeTableRegex`, `ExcludeTableRegex`).
The rationale for implementing this, is that we noticed that quite a bit of compute went to parsing JSON fields, even though we were not listening to any tables containing JSON fields. This PR should fix that.

Skip decoding of excluded table rows

---

replication/binlogstreamer.go
replication/binlogsyncer.go
replication/parser.go
replication/row_event.go

I have a hacked version of MySQL which has a UDF optional meta in table map event. I managed to add a TableMapOptionalMetaDecodeFunc to decode the optional meta.

Add a optional function to decode optional meta of table map event

---

canal/handler.go
canal/sync.go

Hi.
I think it will be a great additional feature to have OnRowsQueryEvent
When binlog_rows_query_log_events=ON - you'll get the original executed query, with comments if present.

Add OnRowsQueryEvent to EventHandler

---

Makefile
client/pool.go
client/pool_options.go
client/pool_test.go

client/pool does not report connection problems properly: in cases of authorization errors, version incompatibility, incorrect database address, network problems, etc.
Also, we have https://github.com/go-mysql-org/go-mysql/pull/701 with a request for new functionality in the same case.
This PR updates the pool logic a bit: more user-friendly function `NewPoolWithOptions`, and option `WithNewPoolPingTimeout` for doing connect&ping during pool initialization.
Also, this fixes `make test-local` after https://github.com/go-mysql-org/go-mysql/pull/803.

Update client pool logic

---

canal/sync.go
replication/binlogstreamer.go
replication/event.go
replication/parser.go
replication/row_event.go

I find some codes abount binlog, which is doing slices assignment or append could be simply changed, so that we can get some perfomance tuning.
Hope that it could help
some corresponding benchmark code may be as follow:
```
package main_test
import (
"testing"
)
func BenchmarkAppend(b *testing.B) {
strs := []string{"a", "b", "c"}
tmp := make([]string, 0, len(strs))
b.ResetTimer()
for i := 0; i < b.N; i++ {
for _, str := range strs {
tmp = append(tmp, str)
}
}
}
func BenchmarkAssign(b *testing.B) {
strs := []string{"a", "b", "c"}
tmp := make([]string, len(strs))
b.ResetTimer()
for i := 0; i < b.N; i++ {
for i, str := range strs {
tmp[i] = str
}
}
}
```

tune slice append performance

---

mysql/mariadb_gtid.go
mysql/mariadb_gtid_test.go

ref https://github.com/pingcap/tiflow/issues/10741

separate serverID of Mariadb GTID set

---

mysql/mariadb_gtid.go
mysql/mariadb_gtid_test.go

I am sorry evolved this bug in https://github.com/go-mysql-org/go-mysql/pull/852
"0-1-1,0-2-2", "0-2-2" could be viewed as equal

Fix comparison bug in MariadbGTIDSet.Equal() function

---

canal/rows.go
canal/rows_test.go

fix: (*RowsEvent).handleUnsigned()  panic

---

canal/canal.go

Execute some query when mysql host is down or unavailable will set `c.conn = nil ` and it case panic when close canal client.
https://github.com/go-mysql-org/go-mysql/blob/f0df38a3258e781900cafb36c1887cc9e71e9089/canal/canal.go#L521-L526

Fix close canal client panic if use Execute after mysql host down

---

client/auth.go
client/auth_test.go
client/client_test.go
client/conn.go

This PR is to allow the collation to be set during the auth handshake in order to avoid requiring calls to `SET NAMES` post connection.

allow setting the collation in auth handshake

---

.golangci.yml
client/auth.go
client/auth_test.go
client/conn.go

Fix for https://github.com/go-mysql-org/go-mysql/issues/864
This adjustment reverts an earlier change that made the collation in the auth handshake 2 bytes. Now it follows the MySQL packet specification and is 1-byte. If the collation has a ID of > 255 then `SET NAMES ...` is called after establishing the connection.

collation in auth handshake are 1-byte

---

replication/binlogsyncer.go

We encountered a stuck issue caused by `BinlogSyncer.close()`:
There is "syncer is closing" in log, but no "syncer is closed".
```
[info] binlogsyncer.go:206 syncer is closing...
```
Here are parts of the goroutines:
```
1   100% |   github.com/go-mysql-org/go-mysql/client.ConnectWithDialer github.com/go-mysql-org/go-mysql@v1.6.1-0.20221223014230-81966e15b9c5/client/conn.go:109
0     0%   100%          1  0.89%                | github.com/go-mysql-org/go-mysql/client.(*Conn).handshake github.com/go-mysql-org/go-mysql@v1.6.1-0.20221223014230-81966e15b9c5/client/conn.go:118
1   100% |   github.com/go-mysql-org/go-mysql/client.(*Conn).readInitialHandshake github.com/go-mysql-org/go-mysql@v1.6.1-0.20221223014230-81966e15b9c5/client/auth.go:31 …
```

set read deadline for new conection to fix handshake stuck

---

.golangci.yml
packet/conn.go

This is a fix for https://github.com/go-mysql-org/go-mysql/issues/862

fixing bad connection error when reading large compressed packets

---

.github/workflows/ci.yml

- ~~Add Ubuntu 24.04~~
- ~~Remove Ubuntu 20.04~~
- Add Go 1.22
- Remove Go 1.20, 1.19
- Update checkout action version
- Update setup-go action version
- Update golangci-lint-action version

CI: Update ci workflow

---

canal/sync.go
replication/backup_test.go
replication/replication_test.go

Ref #866 
This fixes the failed tests. This doesn't yet fix other places where we use the old terms.

Use new terms for replication on MySQL 8.4.0

---

client/client_test.go
packet/conn.go

This addresses https://github.com/go-mysql-org/go-mysql/issues/871

fix 'invalid compressed sequence' error, issue #871

---

.github/workflows/ci.yml

Test with MySQL v8.0.37 and v8.4.0 containers.

CI: Add tests for various MySQL versions

---

canal/sync.go

When using the canal package with a MySQL instance with `binlog-transaction-compression=ON`, the following error occurs when you execute an INSERT statement on a table:
```
[2024/05/07 17:30:01] [info] sync.go:237 table structure changed, clear table cache: test_database.employees
panic: interface conversion: replication.Event is *replication.QueryEvent, not *replication.RowsEvent
goroutine 1 [running]:
github.com/go-mysql-org/go-mysql/canal.(*Canal).handleRowsEvent(0x140002ee0e0?, 0x1400049a180?)
/Users/lulusheng/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.7.1-0.20240507101235-8d4de0fa6687/canal/sync.go:253 +0x2a4
github.com/go-mysql-org/go-mysql/canal.(*Canal).runSyncBinlog(0x140002ee0e0)
/Users/lulusheng/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.7.1-0.20240507101235-8d4de0fa6687 …
```

Fix bug in handling sub events of replication.TransactionPayloadEvent

---

client/auth.go
mysql/const.go

Closes #876 
MySQL has:
- Protocol version 9 (very very old on port 3306/tcp)
- Protocol version 10 (a.k.a. Classic Protocol on port 3306/tcp)
- Protocol version 11 (X Protocol, this is a new protocol (protobuf based) and on port 33060/tcp)
When connecting to port 33060 instead of 3306 by mistake the version check didn't return an error when it should have.
```
$ go run go-mysql-876.go 
2024/05/13 22:08:39 failed to query: readInitialHandshake: invalid protocol version 11, expected 10. This might be X Protocol, make sure to connect to the right port
exit status 1
```
```go
package main
import (
"database/sql"
"log"
_ "github.com/go-mysql-org/go-mysql/driver"
)
func main() {
db, err := sql.Open("mysql", "root@127.0.0.1:33070")
if err != nil {
log.Fatalf("failed to connect to mysql: %s", …
```

Make protocol version check more strict

---

README.md
driver/driver.go
driver/driver_options_test.go

This PR is to address issue https://github.com/go-mysql-org/go-mysql/issues/886, which prevents a client from using custom value types, specifically `uint64` in prepared statements.

add support for driver.NamedValueChecker on driver connection

---

README.md
client/auth.go
driver/driver.go
driver/driver_test.go

I noticed that a DSN like this:
```
db.example.com:3307/db?ssl=true
```
would incorrectly have the property `db` in the `connInfo` object set to `ssl=true` when it should have been set to `db`.
According to the README the DSN format allows for an optional `user:password@`.
```
[user[:password]@]addr[/db[?param=X]]
```
Adding unit tests for the `ParseDSN` function to cover those cases.

Support DSN without 'user:password@'

---

mysql/util.go
mysql/util_test.go

This PR improves the string formatting of time type columns, `FormatBinaryTime` does not return properly formatted time strings in all cases. 
In the zero value case, it was incorrectly returning a `date` formatted string instead of the expected zero `time` of `00:00:00`. For positive times there was a leading null byte in the returned []byte.
`CREATE TABLE time_test (ts TIME);`
`INSERT INTO time_test (ts) VALUES ("00:00:00"), ("06:12:10");`
Reading the values out (using a statement as direct queries don't use FormatBinaryTime) 
`SELECT * FROM %s WHERE ts > ?`
with query parameter `-5` or some other number
resulted in
```
"0000-00-00"
"\x0006:12:10"
```
when the expected result is
```
"00:00:00"
"06:12:10"
```

time column type string formatting and test coverage

---

client/auth.go
client/conn.go
driver/driver_options_test.go
packet/conn.go

Our usage of this library is in an application that will maintain a few thousand active MySQL connections from a single instance and we've noticed that the application is holding a lot of memory in `packet.Conn`, specifically the `bufio.Reader` instances are holding about 500MB of the total 800MB heap.
This PR will allow our application to change the hardcoded `65536` buffer size to something more reasonable for our use case (maybe `4096`), which should reduce our heap by at least 50%.

allow packet.Conn buffer size to be adjustable

---

canal/sync.go

After upgrading to MariaDB 11.4.1, the canal module stopped detecting row updates within transactions due to incorrect handling of fake rotate events. MariaDB 11.4.1 does not set LogPos for certain events, causing these events to be ignored. This fix modifies the handling to consider fake rotate events only for ROTATE_EVENTs with timestamp = 0, aligning with MariaDB and MySQL documentation.
Consequences of this change:
* Events with LogPos=0 that are not of type ROTATE_EVENT will no longer be ignored.
* If a database does not set timestamp=0 for fake rotate events, these events will be processed as real rotate events.
For MariaDB 11.4, I have confirmed that the timestamp for fake rotate events is set to 0. Based on the MariaDB and MySQL source code and documentation, I believe we can rely …

fix(canal): do not ignore events with LogPos=0, use timestamp to distinguish fake rotate events

---

README.md
canal/sync.go
driver/driver.go
driver/driver_options_test.go

We've run into a problem caused by the Golangs `database/sql` package [default retry behavior](https://github.com/golang/go/blob/c5430dc1d8d96cfd0c85a6d760262676d798a6a9/src/database/sql/sql.go#L1663) (which can't be disabled by the way) when an [ErrBadConn](https://pkg.go.dev/database/sql/driver@go1.22.5#ErrBadConn) from the `database/sql/driver` is returned by the driver. We're looking to have our application fail fast when an issue occurs reaching the DB, but as of now we're seeing 3 retries, causing our application to hang up longer than we'd like.
Seems like others in the community have been asking for a way to disable retries, see https://github.com/golang/go/issues/52886 but the go developers have decided to not allow developers to configure that behavior.
This PR makes use of the …

allow disabling the default golang database/sql retry behavior

---

canal/canal_test.go
canal/config.go
canal/sync.go

`ANALYZE TABLE` was not being considered in DDL statements.
This is a problem because if it doesn't return as one of the nodes from `parseStmt()` then it won't set `savePos` to `true` here:
https://github.com/go-mysql-org/go-mysql/blob/3b1dd0e7703815062f7999fd7d503df0061807a9/canal/sync.go#L157-L182
Which means the binary log doesn't advance.
We rely on the binary log to advance to implement our own `BlockWait()` function, which is similar to `c.WaitUntilPos()`. We can't use `WaitUntilPos()` because it calls `FLUSH BINARY LOGS` which requires additional privileges.
We were previously injecting binlog noise to advance the binary log, but with this fix we shouldn't need to do that (and ideally `WaitUntilPos()` doesn't either, so it can catch bugs if statements are left off the list like …

Add `DisableFlushBinlogWhileWaiting` config and almost every query event triggers `OnPosSynced`

---

schema/schema.go
schema/schema_test.go

For developers using multi-value indexes, the column name as reported by `show index...` is null.
Closes https://github.com/go-mysql-org/go-mysql/issues/903

Handle null index column names in sql.DB loader

---

canal/canal.go
canal/config.go

use `Canal` to sync binlog may get OOM if binlog contain large column, that because BinlogStreamer default internal channel too large, set EventCacheCount to small value can reduce memory usage, but it not exported on `canal.Config` struct.

export EventCacheCount on Canal Config

---

client/auth.go
client/client_test.go

close https://github.com/go-mysql-org/go-mysql/issues/911
Seems we should not use the ending zero in the scramble

Fix can't connect to MySQL 8.0 with long password

---

client/auth.go

This commit fixes `(*client.Conn).writeAuthHandshake()` to use `packet.NewConnWithTimeout` instead of `packet.NewBufferedConn` when recreating the packet connection after switching TLS on. This preserves the connection read/write timeout settings which would otherwise be reset to zero.
Since this code executes after some reads and writes have already taken place, and the packet connection code only sets a deadline when the timeout values are nonzero, the result was that previously when connecting using TLS and with a read and/or write timeout set, the connection would inevitably fail just one timeout-duration after being opened.
This use of `packet.NewBufferedConn` appears to be the only place in the `client` package where a packet connection was recreated without the timeout …

client: Fix timeout reset during TLS handshake

---

replication/binlogsyncer.go

```
$ ./bin/go-mysqlbinlog  | head
[2024/10/27 10:29:18] [info] binlogsyncer.go:189 create BinlogSyncer with config {ServerID:101 Flavor:mysql Host:127.0.0.1 Port:3306 User:root Password: Localhost: Charset: SemiSyncEnabled:false RawModeEnabled:false TLSConfig:<nil> ParseTime:false TimestampStringLocation:UTC UseDecimal:true RecvBufferSize:0 HeartbeatPeriod:0s ReadTimeout:0s MaxReconnectAttempts:0 DisableRetrySync:false VerifyChecksum:false DumpCommandFlag:0 Option:<nil> Logger:0xc00013c240 Dialer:0x6d1be0 RowsEventDecodeFunc:<nil> TableMapOptionalMetaDecodeFunc:<nil> DiscardGTIDSet:false EventCacheCount:10240 SynchronousEventHandler:<nil>}
[2024/10/27 10:29:18] [info] binlogsyncer.go:429 begin to sync binlog from position (, 4)
[2024/10/27 10:29:18] [info] binlogsyncer.go:407 Connected …
```

replication: Log info about server

---

cmd/go-mysqldump/main.go

Issue: ref #940 
When running against MariaDB 11.4 without binlogs enabled:
- `mysqldump` 9.1.0 fails to dump when called with `--source-data` due to the `SHOW BINARY LOG STATUS` not being supported by MariaDB.
- `mariadb-dump` 11.4 fails to dump when called with `--master-data` due to binlogs not being enabled.
Other situations where this can be useful:
- Permission issues

go-mysqldump: Add option to skip binlog position

---

cmd/go-mysqlbinlog/main.go
replication/binlogsyncer.go

1. Set `MaxReconnectAttempts: 10` for `go-mysqlbinlog`
2. Print retry nr & max on retry
```
...
=== MariadbBinLogCheckPointEvent ===
Date: 2024-11-08 14:05:51
Log position: 329
Event size: 44
Info: mysqld-bin.000002
[2024/11/08 14:05:56] [info] binlogsyncer.go:800 receive EOF packet, no more binlog event now.
[2024/11/08 14:05:56] [error] binlogsyncer.go:728 io.ReadFull(header) failed. err EOF: connection was bad
[2024/11/08 14:05:57] [info] binlogsyncer.go:659 begin to re-sync from (mysqld-bin.000002, 329)
[2024/11/08 14:05:57] [error] binlogsyncer.go:757 retry sync err: dial tcp 127.0.0.1:3307: connect: connection refused, wait 1s and retry again (retries: 1/10)
[2024/11/08 14:05:58] [info] binlogsyncer.go:659 begin to re-sync from (mysqld-bin.000002, 329)
[2024/11/08 14:05:58] [error] …
```

go-mysqlbinlog: set to retry only 10 times

---

cmd/go-mysqldump/main.go
dump/dumper.go

Issue: ref #940 closes #264
- Call `mariadb-dump` when there is no `mysqldump` in the execution path
- This also fixes the issue that `dump.NewDumper()` might return `nil, nil` and `go-mysqldump` not checking for that.

dump: use mariadb-dump when available

---

.github/workflows/ci.yml
canal/canal.go
canal/canal_test.go
dump/dumper.go
mysql/const.go

canal: 
* address format support ipv6 with port like `[::1]:3306` in canal
* parse ipv6 address with optional port like `::1` or `[::1]:3306` in dumper

canal: support ipv6 address

---

replication/const.go

Issue: ref #845 
The `GTID_TAGGED_LOG_EVENT` was added in MySQL 8.3
This only adds the `EventType`, but it doesn't yet do any decoding.
Example output from `go-mysqlbinlog`:
```
=== Gtid_tagged_log_event ===
Date: 2024-11-12 21:51:23
Log position: 220908
Event size: 83
Event data: 
00000000  02 78 00 00 00 02 aa aa  aa aa 88 88 66 66 44 44  |.x..........ffDD|
00000010  22 22 22 22 22 22 04 73  20 1b 06 14 73 65 63 6f  |"""""".s ...seco|
00000020  6e 64 74 65 73 74 08 c1  0e 0a d1 0e 0c 7f 23 35  |ndtest........#5|
00000030  48 61 bd 26 06 10 59 04  12 a3 ff 0a              |Ha.&..Y.....|
```

replication: Add GTID_TAGGED_LOG_EVENT

---

README.md

Fix example
Otherwise this happens:
```
./main.go:60:22: not enough arguments in call to sql.Open
have (string)
want (string, string)
```
See also https://pkg.go.dev/database/sql#Open

README: fix example for database/sql

---

mysql/field.go

In my use case, I have a kind of MySQL proxy that can modify values for certain fields, but I couldn't find an API that allows this. So, I came up with this solution, which can be used as follows:
```
func (p *Proxy) HandleStmtExecute(context interface{}, query string, args []interface{}) (*mysql.Result, error) {
var stmt *client.Stmt
//...
res, err := stmt.Execute(args...)
//...
res.Values[row][column] = mysql.NewFieldValue(mysql.FieldValueTypeUnsigned, rawGUID, []byte(fmt.Sprintf("%d", rawGUID)))
return res, nil
}
```

mysql field: expose API to modify field value

---

cmd/go-canal/main.go

1. Remove duplicate SIGINT from signal.Notify call
2. Keep other signal handlers (SIGHUP, SIGTERM, SIGQUIT) unchanged

Remove duplicate SIGINT in signal handling

---

.golangci.yml
client/conn.go
client/examples_test.go

1. Add comments to `GetServerVersion` and `CompareServerVersion`.
2. Move examples to a separate file. 
- godoc can find them there and do proper formatting etc.
- As no expected output is included and these can't be run individually, this is not yet [a testable example](https://go.dev/blog/examples)
- This fixed the formatting (old formatting can be seen on https://pkg.go.dev/github.com/go-mysql-org/go-mysql@v1.10.0/client#Conn.ExecuteMultiple )

client: Update docs

---

mysql/resultset.go
mysql/resultset_test.go

Example code:
```go
package main
import (
"github.com/go-mysql-org/go-mysql/client"
)
func main() {
conn, _ := client.Connect("127.0.0.1:3307", "root", "", "test")
r, _ := conn.Execute(`SELECT SUM(-1)`)
v, err := r.GetInt(0, 0)
if err != nil {
panic(err)
}
println(v)
}
```
Without this PR:
```
$ go run main.go 
panic: strconv.ParseUint: parsing "-1": invalid syntax
goroutine 1 [running]:
main.main()
/tmp/getint/main.go:12 +0xb1
exit status 2
```
With this PR:
```
-1
```
From Wireshark:
From MySQL Client:
```
mysql-8.4.3> SELECT SUM(-1);
Field   1:  `SUM(-1)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     24
Max_length: 2
Decimals:   0
Flags:      BINARY NUM 
+---------+
| SUM(-1) |
+---------+
|      -1 | …
```

mysql: Fix GetInt() with negative NEWDECIMAL result

---

client/auth.go
client/conn.go
client/conn_test.go
client/stmt.go
mysql/const.go
mysql/queryattributes.go
mysql/queryattributes_test.go
server/stmt.go
server/stmt_test.go

Just like connection attributes, there are also query attributes in MySQL. These allow one to pass key/value pairs along with queries. 
These can be used to add metadata about:
- The page being rendered
- The user for the proxy connection
- A trace ID for debugging
- A shard-id hint
- A follower-read setting
- An application stack listing
- The line of the application code sending the query
- https://dev.mysql.com/doc/refman/8.4/en/query-attributes.html
- https://archive.fosdem.org/2021/schedule/event/mysql_protocl/
In some other languages, etc:
```
mysql-9.2.0> query_attributes proxy_user myuser page index.html
mysql-9.2.0> SELECT mysql_query_attribute_string('proxy_user'), mysql_query_attribute_string('page');
+--------------------------------------------+-------------------------------- …
```

client,mysql: Add support for Query Attributes

---

mysql/result.go
mysql/result_test.go
server/resp.go

This is likely a regression introduced by #969 
Found by running this code: https://github.com/go-mysql-org/go-mysql/issues/915#issuecomment-2640067648
Queries like `SELECT 1` were working correctly, but `DO 1` and `SET ...` were not as the code tried to write a resultset instead of an OK.

server: Correct the check for Resultset

---

client/auth.go
client/conn.go
client/resp.go
client/stmt.go
dump/dumper.go
packet/conn.go
replication/backup.go
replication/binlogsyncer.go
replication/event.go
replication/json_binary.go
replication/row_event.go
replication/transaction_payload_event.go
server/auth.go
server/auth_switch_response.go
server/command.go
server/conn.go
server/handshake_resp.go
server/resp.go
server/server_conf.go
server/stmt.go

The dot import might confuse both tools and users
Example:
https://pkg.go.dev/github.com/go-mysql-org/go-mysql@v1.11.0/client#Conn.Execute
With this PR (locally via godoc):
Note that it now is able to turn the `Result` in a link.
Resources:
- https://go.dev/wiki/CodeReviewComments#import-dot

Change how we import the mysql package

---

README.md

preview https://github.com/go-mysql-org/go-mysql/blob/3406f1ec2f3bb90e87f49f5b645fabd949d8afaa/README.md

README: add Platform Support section

---

server/stmt.go

Closes #915 
Tested with sysbench 1.0.20

server: Correctly handle COM_STMT_EXECUTE without rebind

---

.github/workflows/ci.yml
.golangci.yml

`allow-leading-space: false` is not valid config anymore
```
$ golangci-lint config verify
jsonschema: "linters-settings.nolintlint" does not validate with "/properties/linters-settings/properties/nolintlint/additionalProperties": additionalProperties 'allow-leading-space' not allowed
Failed executing command with error: the configuration contains invalid elements
```
Also allow annotations:
https://github.com/golangci/golangci-lint-action/tree/v6/?tab=readme-ov-file#annotations
Needed for annotations to work:
- Permission
- setup-go (for the problem matcher)
Also set the Go version to 'stable' instead of a specific version and add 1.24 to the list.

CI: Update nolintlint config

---

README.md
client/example_client_test.go

This removes the client example from the README and puts it in its own file.
The benefits of this:
- This makes this a [testable example](https://go.dev/blog/examples)
- This shows up in the godoc documentation
The drawbacks of this:
- It isn't in the README anymore
- This might be a bit weird for server examples that need the MySQL client. But there we could just have no output.
Issues found with the example while doing this:
1.  Missing import for `github.com/go-mysql-org/go-mysql/mysql` (it uses `mysql.FieldValueTypeFloat`)
2. The example uses a table named `table`, which is confusing.
3. The example doesn't create the table
4. The `defer r.Close()` should probably be moved higher up
5. The `r.GetInt()` and `r.GetIntByName()` probably need more explanation
6. The test for the float …

client: Make example testable

---

client/conn.go
driver/driver.go
packet/conn.go

`database/sql` `QueryContext` falls back to checking if context is done before calling `Query`, so query does not get cancelled when context is cancelled once execution starts
[driver.Queryer is deprecated](https://cs.opensource.google/go/go/+/refs/tags/go1.24.0:src/database/sql/driver/driver.go;l=203)
Unfortunately supporting this on top of net.Conn requires a goroutine. But that goroutine can be shared across lifetime of connection since connection doesn't need to be threadsafe
To cancel ongoing Read/Write the connection is closed when context finishes
At the end of the function active context is switched to `context.Background()`. Some error handling could be implemented around receiving non-background context when active context is a non-background context, as that implies thread …

driver: context support

---

client/auth.go
go.mod
go.sum
mysql/const.go
mysql/util.go

MariaDB doesn't support `caching_sha2_password` or `sha256_password` authentication plugins, and instead has a completely different `client_ed25519` plugin, which uses a modified version of the ED25519 algorithm. MariaDB recommends using this over `mysql_native_password`.
This PR implements support for `client_ed25519`. The bulk of this PR is taken from https://github.com/go-sql-driver/mysql/pull/1518 with the author's permission. 
Co authored with: @Gusted

add support for MariaDB ED25519 plugin

---

replication/binlogsyncer.go

See also: https://github.com/mysql/mysql-server/blob/6b6d3ed3d5c6591b446276184642d7d0504ecc86/libchangestreams/src/lib/mysql/cs/reader/binary/mysqlproto.cpp#L66
I noticed the difference when looking at packet captures with Wireshark

replication: Set source_binlog_checksum as well

---

server/caching_sha2_cache_test.go

close #988
check a counter to verify cache really takes effect

test: remove time-based checking

---

CONTRIBUTING.md

Initial contributor guide

---

mysql/gtid.go
mysql/mariadb_gtid.go
mysql/mariadb_gtid_test.go
mysql/mysql_gtid.go
mysql/mysql_test.go

Small quality of life improvement. For some use cases (such as writing tests), it is common to want to check if a given GTID set is empty or not. Currently this requires using `Equal()` with an empty GTID set (which takes a decent amount of boilerplate) or else requires inspecting the `Set` field (which is specific to a single concrete implementation of the `GTIDSet` interface).
This commits adds a simple `IsEmpty() bool` method to the `GTIDSet` interface for this use case, as well as implementations for both `MysqlGTIDSet` and `MariadbGTIDSet`.

replication: add IsEmpty method to GTIDSet interface & implementations

---

cmd/go-mysqlserver/main.go
driver/driver_options_test.go
server/conn.go
server/server_conf.go

Closes #1020 
- De-duplicate `NewConn()` and `NewCustomizedConn()` code
- Only call `NewDefaultServer()` when needed

server: Rework NewConn/defaultServer

---

server/credential_provider.go

Fixes this:
An alternative:
```patch
diff --git a/server/credential_provider.go b/server/credential_provider.go
index 3d44eb0..5333f89 100644
--- a/server/credential_provider.go
+++ b/server/credential_provider.go
@@ -4,7 +4,9 @@ import "sync"
// interface for user credential provider
// hint: can be extended for more functionality
+//
// =================================IMPORTANT NOTE===============================
+//
// if the password in a third-party credential provider could be updated at runtime, we have to invalidate the caching
// for 'caching_sha2_password' by calling 'func (s *Server)InvalidateCache(string, string)'.
type CredentialProvider interface {
```

server: Fix formatting of credential provider note

---

.github/workflows/ci.yml
.golangci.yml
client/conn.go
client/conn_test.go
client/resp.go
driver/driver.go
dump/dumper.go
mysql/result.go
replication/backup.go
replication/binlogsyncer.go
replication/parser.go
replication/row_event.go
schema/schema.go
server/auth.go
server/auth_switch_response.go

changes mostly result of
```sh
golangci-lint migrate
golangci-lint run --fix
```

golangci-lint 2

---

client/auth.go
client/conn.go

https://github.com/masahide/mysql8-audit-proxy/issues/8
A common architecture for a MySQL **audit / filter / router** built on *go-mysql* looks like this:
```
[application] -- go-mysql/server  -->  [proxy]  -- go-mysql/client -->  [mysqld]
```
* **Downstream side** (`go-mysql/server`)
*Implements the old 5.7/8.0 protocol* and **does not recognise
`CLIENT_QUERY_ATTRIBUTES`**.
When an application connects, the handshake therefore has the bit **cleared**.
* **Upstream side** (`go-mysql/client` ≥ v1.12.0)
In `writeAuthHandshake()` the client **automatically copies
`CLIENT_QUERY_ATTRIBUTES` from the server greeting**, claiming the proxy
will send query attributes.
* **Mismatch**
The proxy simply forwards the raw `COM_QUERY` it received from the
application.
Because the downstream never added …

client: make CLIENT_QUERY_ATTRIBUTES opt-out to restore proxy compatibility

---

canal/canal.go
canal/sync.go
replication/parser.go

not sure why there's no atomic.NewUint32,
so leave baseConnID alone

prefer atomic values to atomic operations

---

replication/row_event.go
replication/row_event_test.go
replication/time.go

MySQL supports 0 for day/month when this is an unknown value
This cannot be encoded into a time.Time, where time.Date normalizes these 0s (so 2000-00-00 would become 1999-11-30)
Pass these values through in their raw string form instead, like we do for 0000-00-00

replication: return string when datetime's day or month is 00
