replication/row_event.go
For request of this kind:
"UPDATE `table_name` SET field="foo" LIMIT 10"
=> Multiply rows for event rows

replication/binlogsyncer.go
There was a small error in the last pull request. This fixes that error.
=> Slave hostname

Makefile, replication/replication_test.go, replication/row_event.go
=> fix row decode panic

canal/canal.go, canal/handler.go, canal/master.go, canal/sync.go, driver/driver.go, dump/parser.go, failover/server.go, mysql/util.go
We use juju errors, so can' use `==` and `!=` to check error directly. 
@qiuyesuifeng
=> *: use ErrorEqual to check error.

schema/schema.go
=> schema: use prefix to check time precision.

canal/canal.go, canal/canal_test.go, canal/config.go, failover/failover_test.go
=> *: ignore mysqldump if not set.

README.md, canal/canal.go, cmd/go-mysqlbinlog/main.go, replication/backup.go, replication/binlogstreamer.go, replication/binlogsyncer.go, replication/replication_test.go
=> *: support re-sync when connection was bad.

README.md, canal/sync.go, cmd/go-mysqlbinlog/main.go, glide.lock, glide.yaml, replication/backup.go, replication/binlogstreamer.go, replication/replication_test.go, vendor/golang.org/x/net/LICENSE, vendor/golang.org/x/net/PATENTS, vendor/golang.org/x/net/context/context.go
=> *: refactor with Context.

README.md, canal/sync.go, replication/backup.go, replication/replication_test.go
=> *: fix wrong use of context.

replication/binlogsyncer.go
=> replication: log rotate.

replication/binlogsyncer.go, replication/parser.go
=> replication: must reset parser before retry.

replication/parser.go
=> replication: tables can only be cleared with RowsEventStmtEndFlag

replication/binlogsyncer.go
=> replication: handle EOF packet.

dump/dump_test.go, dump/parser.go
To fix https://github.com/siddontang/go-mysql/issues/95
@qiuyesuifeng
=> dump: use non greedy capture.

replication/json_binary.go, replication/replication_test.go, replication/row_event.go
Parse MySQL JSON binary encoding data and covert to common JSON string. 
PTAL @qiuyesuifeng @shlomi-noach @palexvs
=> support json type

schema/schema.go
=> Add raw type of column in schema

canal/canal.go, replication/binlogsyncer.go, replication/parser.go, replication/replication_test.go, replication/row_event.go, replication/time.go, replication/time_test.go, schema/schema.go
@shlomi-noach 
I support a ParseTime config to decode timestamp and datetime to a Time structure.
=> support parse time config

README.md, canal/canal.go, canal/canal_test.go, canal/config.go, canal/dump.go, canal/handler.go, canal/master.go, canal/sync.go, cmd/go-canal/main.go
1. Remove master info saved, let user do it outside
2. Add Handlers
3. Introduce context for later refactor
=> canal: refactor canal

canal/rows.go
add function of get term field's value by field name
=> add function of get term field's value by field name

replication/binlogsyncer.go
=> Add LogLevel in BinLogSyncerConfig

mysql/mysql_gtid.go
=> ParseMysqlGTIDSet should handle str is empty

mysql/mysql_gtid.go
=> AddSet should handle nil uuidset

canal/canal.go, canal/config.go, canal/dump.go, canal/sync.go, dump/dump.go, dump/dump_test.go, dump/parser.go
Skip master data if we have no privilege to dump the data with it in some cloud MySQL.
=> skip master data

canal/canal_test.go, canal/sync.go
ref https://github.com/siddontang/go-mysql/issues/153
=> Handle rename table event

canal/canal.go, canal/dump.go, canal/handler.go, canal/sync.go, cmd/go-canal/main.go
add save master info interface
=> add save master info interface

README.md, canal/canal.go, cmd/go-mysqlbinlog/main.go, replication/binlogsyncer.go, replication/replication_test.go
=> ignore password output

replication/event.go
This is the new code using const variables .
=> Add two member to GTID event

replication/binlogsyncer.go
after slave send ack to master, master will not reply
this is fix for https://github.com/siddontang/go-mysql/issues/176
=> fix bug in semi sync

canal/canal.go, canal/config.go, canal/sync.go, schema/schema.go
[modify] do not stop canal when get table meta error
[modify] work around for RDS ha_health_check
=> fault tolerance for fetching table meta error in canal

canal/canal.go, canal/canal_test.go, canal/config.go, canal/dump.go, canal/sync.go
add include and exclude regex filter for canal
add filter cache for better match performance
=> add table regex filter for canal

README.md
=> fix typo of README

driver/dirver_test.go
Add database parameters to driver_test for local test using different password for MySQL.
=> add database parameters to driver_test

dump/dump.go, dump/parser.go
on windows someone end with '\r\n'
on linus end with '\n'
we not want '\n' or '\r\n'
=> trim '\r\n' or '\n'

dump/dump.go, dump/parser.go
mysqldump param should be --max-allowed-packet=%dM not be --max_allowed_packet=%dM
=> mysqldump param should be --max-allowed-packet=%dM not be --max_allowed_packet=%dM

canal/canal_test.go, canal/sync.go
ref https://github.com/siddontang/go-mysql/issues/227
=> Capture create table DDL on `QueryEvent`

dump/dump.go, replication/parser.go
- adding propery 'exit bool';
- adding function SetExit to control it.
=> should be possible to exit from processing file when conditions met

canal/canal.go, canal/dump.go, canal/sync.go, dump/dump.go, replication/binlogsyncer.go
#260 work in progress. This passes our internal tests.
=> FEATURE: add dump and sync with gtid

README.md
=> Fixed typo in comment

replication/json_binary.go, replication/row_event_test.go
=> return empty slice for the invalid NULL JSON

canal/sync.go, failover/mariadb_gtid_handler.go, mysql/mariadb_gtid.go, mysql/mariadb_gtid_test.go
leave canal still only support single source replication
=>  *: support multiple sources replication for mariadb

canal/dump.go, canal/rows.go, canal/sync.go
This PR is exposes the binlog header info in the rows event. For use we really want the Timestamp of the event
Thanks!
=> add header to rows event

replication/row_event.go
=>  binlog: parse error when timestamp is "0000-00-00 00:00:00" or datetime is "0000-00-00 00:00:00" (#254)

replication/parser.go
@siddontang  @GregoryIan  PTAL
=> export parseSingleEvent and check error

canal/config.go
=> [Fix] some toml config have no effect

mysql/mariadb_gtid.go, mysql/mariadb_gtid_test.go, mysql/mysql_gtid.go
*: make real clone for mysql gtid set
*: remove limit of mariadb gtid sequence number increment
@siddontang PTAL
=> some bugfixs for gtid

replication/binlogstreamer.go
ref #325 
新增的一个func，你检查一下哈，谢谢。
=> add GetEventWithStartTime

canal/dump.go, cmd/go-canal/main.go, cmd/go-mysqlbinlog/main.go, replication/replication_test.go, schema/schema.go, schema/schema_test.go
Decimal is not the same as float, provide a Decimal type to let the user handle it explicitly, not already use float instad.
=> support Decimal type

client/resp.go, packet/conn.go
=> fix: remove unused cgo

canal/canal.go, canal/config.go, dump/dump.go
Ref: https://github.com/siddontang/go-mysql/pull/352
Adding support for the canal tool to also use protocol.
=> Add support for the protocol argument in canal

replication/const.go, replication/event.go, replication/event_test.go
see for details https://github.com/siddontang/go-mysql/issues/418
=> issue 418: surfacing MariadbGTIDEvent.Flags

client/resp.go, client/stmt.go, mysql/result.go, server/caching_sha2_cache_test.go, server/conn.go, server/resp.go, server/server_test.go
Support for this used to exist but was disabled/removed for some reason. This PR reads number of warnings in the client-side code and allows you to set the number of warnings on the server-side.
=> Support for number of warnings in OK and EOF

server/resp.go, server/resp_test.go, test_util/conn/mockconn.go
and added the tests to back it up
=> applied small refactor writeResultSet to minimize code duplication

client/resp.go
=> fix: return error if error in packet

mysql/util.go, server/conn.go, server/resp.go
=> optim: remove useless return value for mysql.util.RandomBuf

.github/workflows/ci.yml
Added go1.19 test to GitHub Actions
=> Add go1.19 test matrix

canal/canal.go, canal/config.go
according to https://github.com/go-mysql-org/go-mysql/pull/36
I use canal and need to provide localhost option to syncer stream.
=> canal: use localhost option

client/conn_test.go
=> Add test for attributes

canal/canal.go
=> Make SyncedTimestamp goroutine-safe

Makefile
This allows `make GO=gotip build` to work.
=> Makefile: allow for gotip

clear_vendor.sh
=> Cleanup: remove clear_vendor.sh

.github/workflows/ci.yml
- https://github.com/actions/runner-images/issues/11101
- https://github.blog/changelog/2025-02-12-notice-of-upcoming-deprecations-and-breaking-changes-for-github-actions/#ubuntu-20-image-brownouts
=> CI: Remove Ubuntu 20.04

dump/dumper.go
=> dump: Fix Unlick typo

replication/binlogsyncer.go
Ref #866 
https://github.com/mysql/mysql-server/blob/ff05628a530696bc6851ba6540ac250c7a059aa7/sql/rpl_replica.cc#L2856
=> Set source_heartbeat_period as well as master_heartbeat_period.
